spring:
  application:
    name: news-service
  jpa:
    hibernate:
      ddl-auto: update
server:
   port: 8887
app:
  firebase-configuration-file: google/bus-news-notifier-firebase-adminsdk-ubeik-c3aa3fa62c.json